name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer
        extensions: mbstring, xml, ctype, iconv, dom, bcmath, json, pdo, tokenizer

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: |
          vendor/
          ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Copy .env
      run: cp .env.example .env

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Generate application key
      run: php artisan key:generate

    - name: Run migrations
      run: php artisan migrate --env=testing --no-interaction --force
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"

    - name: Run tests
      run: php artisan test --parallel --env=testing