name: Laravel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.2"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: mbstring, xml, ctype, iconv, dom, bcmath, json, pdo, tokenizer

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: |
            vendor/
            ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --env=testing --no-interaction --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"

      - name: Run tests
        run: php artisan test

      - name: Notify success
        if: success()
        env:
         GOOGLE_CHAT_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        run: |
         curl -X POST \
         -H "Content-Type: application/json" \
         -d '{
            "text": "✅ *Laravel CI Pipeline PASSED* ✅\n\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}\n*Commit Message:* ${{ github.event.head_commit.message }}\n*Author:* ${{ github.actor }}\n*Workflow:* ${{ github.workflow }}\n*Run ID:* ${{ github.run_id }}\n\n🎉 All tests passed successfully!"
         }' \
         "$GOOGLE_CHAT_WEBHOOK"
      - name: Notify failure
        if: failure()
        env:
          GOOGLE_CHAT_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "text": "❌ *Laravel CI Pipeline FAILED* ❌\n\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}\n*Commit Message:* ${{ github.event.head_commit.message }}\n*Author:* ${{ github.actor }}\n*Workflow:* ${{ github.workflow }}\n*Run ID:* ${{ github.run_id }}\n\n💥 Pipeline failed. Please check the logs for details.\n\n[View Run Details](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          }' \
          "$GOOGLE_CHAT_WEBHOOK"